---
- name: Playbook for Workstation Setup
  hosts: localhost
  become: true
  become_user: root
  vars:
    ansible_user: tsweets
##  vars_files:
#    - secrets.yml
  roles:
    - bootstrap
    - base
    - role: gantsign.visual-studio-code
#  - system
    - packages
#  - gnome
    - docker
#  - java-dev
#  - devops
#  - tony
