---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
    - name: instance
      image: tsweets/molecule-docker-centos8:latest
      command: ${MOLECULE_DOCKER_COMMAND:-""}
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      privileged: true
      pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
