# Visual Studio Code version number (defaults to the latest version)
visual_studio_code_version: ''

# Build (either 'stable' or 'insiders') https://code.visualstudio.com/insiders/
# Ubuntu only (code-insiders isn't in Microsoft's RPM repo)
visual_studio_code_build: stable

# Mirror server for fetching the public keys and the Visual Studio Code
# installation package. The URL may include directories. The URL must not end
# with a trailing slash.
visual_studio_code_mirror: 'https://packages.microsoft.com'

# should the gpgcheck of the repo enabled?
# if yes
# - for apt repo the option trusted=yes is NOT added
# - for dnf/yum the option gpgcheck is set to yes
# - for zypper the option gpgcheck is set to 1
# yes is the default
# if no
# - for apt repo the option trusted=yes is added to repo definition
# - for dnf/yum the option gpgcheck is set to no
# - for zypper the option gpgcheck is set to 0
visual_studio_code_gpgcheck: yes

# skip task to add repo for remote package manager
# if set to yes, the task 'install VS Code repo (apt/yum/dnf/zypper)' will be skipped
# if set to no, the repo will be added, this is the default
visual_studio_code_skip_add_repo: no

# Users to install extensions for and/or write settings.json
users:
  - username: tsweets # Unix user name
    visual_studio_code_extensions:
      - arcticicestudio.nord-visual-studio-code
      - redhat.ansible
      - eamodio.gitlens
      - ms-python.python
      - ms-vscode-remote.vscode-remote-extensionpack
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-azuretools.vscode-docker
    visual_studio_code_settings_overwrite: # Overwrite the settings file if it exists. Options: boolean "yes" or "no" (defaults to "no").
    visual_studio_code_settings: # JSON object
    visual_studio_code_keybindings_overwrite: # Overwrite the keybindings file if it exists. Options: boolean "yes" or "no" (defaults to "no").
    visual_studio_code_keybindings: # JSON array
